# Generated by Django 3.1.13 on 2021-09-18 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('study_time', models.IntegerField(verbose_name='平均勉強時間')),
                ('level', models.CharField(max_length=200, verbose_name='レベル')),
                ('textbook', models.CharField(max_length=200, verbose_name='参考書名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='参考書表紙')),
                ('content', models.TextField(verbose_name='勉強法')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
