# Generated by Django 3.1.13 on 2021-10-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.part', verbose_name='Part'),
        ),
        migrations.AlterField(
            model_name='post',
            name='study_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studytime', verbose_name='平均勉強時間/日'),
        ),
    ]
