# Generated by Django 3.1.13 on 2021-10-15 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20211016_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='study_posts', to=settings.AUTH_USER_MODEL, verbose_name='参考になった'),
        ),
    ]
