# Generated by Django 3.1.13 on 2021-10-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211031_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='part',
            field=models.CharField(choices=[('Part1', 'Part1'), ('Part2', 'Part2'), ('Part3', 'Part3'), ('Part4', 'Part4'), ('Part5', 'Part5'), ('Part6', 'Part6'), ('Part7', 'Part7')], max_length=200, verbose_name='Part'),
        ),
    ]
