# Generated by Django 3.1.13 on 2021-10-31 18:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211101_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='part',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Part1', 'Part1'), ('Part2', 'Part2'), ('Part3', 'Part3'), ('Part4', 'Part4'), ('Part5', 'Part5'), ('Part6', 'Part6'), ('Part7', 'Part7')], max_length=41, verbose_name='Part'),
        ),
    ]
