# Generated by Django 3.1.13 on 2021-10-31 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211101_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='part',
        ),
        migrations.AddField(
            model_name='post',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.part', verbose_name='Part'),
            preserve_default=False,
        ),
    ]
