# Generated by Django 3.1.13 on 2021-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211101_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='part',
            field=models.ManyToManyField(related_name='post_part', to='app.Part', verbose_name='Part'),
        ),
    ]
