# Generated by Django 3.1.13 on 2021-10-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211101_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='part',
            field=models.ManyToManyField(to='app.Part', verbose_name='Part'),
        ),
    ]
