# Generated by Django 3.1.13 on 2021-11-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211101_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='part',
        ),
        migrations.AddField(
            model_name='post',
            name='parts',
            field=models.ManyToManyField(related_name='post', to='app.Part', verbose_name='Part'),
        ),
    ]
