# Generated by Django 3.1.13 on 2021-11-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211114_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parts',
        ),
        migrations.AddField(
            model_name='post',
            name='part',
            field=models.ManyToManyField(to='app.Part', verbose_name='Part'),
        ),
    ]
