# Generated by Django 3.1.13 on 2021-12-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20211114_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
    ]
