# Generated by Django 3.1.13 on 2021-12-11 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='職業')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='content',
            field=models.CharField(blank=True, max_length=100, verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='初めてのスコア'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='ベストスコア'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ocupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ocupation'),
        ),
    ]
