# Generated by Django 3.1.13 on 2021-10-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='administrator', max_length=30, verbose_name='ニックネーム'),
        ),
    ]
