# Generated by Django 3.1.13 on 2021-12-11 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211211_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(990)], verbose_name='初めてのスコア'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='max_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(990)], verbose_name='ベストスコア'),
        ),
    ]
