# Generated by Django 3.1.13 on 2021-12-11 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211211_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='max_score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_listnig',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(495)], verbose_name='初めてのリスニングスコア'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_reading',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(495)], verbose_name='初めてのリーディングスコア'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_Reading',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(495)], verbose_name='ベストリーディングスコア'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_listning',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(495)], verbose_name='ベストリスニングスコア'),
        ),
    ]
