# Generated by Django 3.1.13 on 2021-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211015_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=30, verbose_name='ニックネーム'),
        ),
    ]
