# Generated by Django 3.1.13 on 2021-12-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211211_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='max_listning',
            new_name='max_listening',
        ),
    ]
