# Generated by Django 3.1.13 on 2021-10-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211015_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default="{% static 'app/img/user.png' %}", null=True, upload_to='images', verbose_name='プロフィール画像'),
        ),
    ]
