# Generated by Django 3.1.13 on 2022-04-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211212_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='max_listening',
            field=models.IntegerField(blank=True, null=True, verbose_name='ベストリスニングスコア'),
        ),
    ]
