# Generated by Django 3.1.13 on 2022-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220419_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_total',
            field=models.IntegerField(default=0),
        ),
    ]
