# Generated by Django 3.1.13 on 2022-04-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220419_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_total',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='max_total',
        ),
    ]
