# Generated by Django 3.1.13 on 2022-04-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220419_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_total',
            field=models.IntegerField(default=0, verbose_name='最高スコア'),
        ),
    ]
