# Generated by Django 3.1.13 on 2022-04-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_max_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_total',
            field=models.IntegerField(default=0, verbose_name='最初のスコア'),
        ),
    ]
